### PR TITLE
Fix docker file

### LINKED ISSUE #31: Handle the situation when report size over Github Action limits
# Overview

See this workflow - https://github.com/vulekamali/budget-spending-data/actions/runs/2589987176 - it seems not to be able to save a report as it's too big

From https://github.com/frictionlessdata/repository/issues/28

### PR DESCRIPTION
**Pull request by shashigharti**
Please make sure that all the checks pass. Please add here any additional information regarding this pull request. It's highly recommended that you link this PR to an issue (please create one if it doesn't exist for this PR)

### CODE REVIEW

**Comment by shashigharti** [comment]
@roll it is ready for review

**Review by roll — APPROVED** [review]
Thanks @shashigharti 

I think we definetely need .dockerignore

**Comment by shashigharti** [comment]
Thank you!. Sorry I forgot to add that change.

**Comment by roll** [comment]
I mean that was a good addition. Merging

**Pull request merged**
